### ISSUE TITLE
No Email and no pictures 

### ISSUE THREAD

**Issue by anonymoushand** [LemmyNet/lemmy-ansible#66]
Using default ansible config, email isn't working (tested with forget password button, just gets stuck) and also trying to upload a picture givers error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Config file:
{
  # for more info about the config, check out the documentation
  # https://join-lemmy.org/docs/en/administration/configuration.html

  database: {
    host: postgres
    password: "{{ postgres_password }}"
  }
  hostname: "{{ domain }}"
  pictrs: {
    url: "http://pictrs:8686/"
    api_key: "{{ postgres_password }}"
  }
  email: {
    smtp_server: "postfix:25"
    smtp_from_address: "noreply@{{ domain }}"
    tls_type: "none"
  }
}

**Comment by dessalines** [comment]
I'm not sure how to debug this without seeing the instance, or the docker logs.

**Comment by akzmonster** [comment]
I would like to see if you can help me with SMTP.

BTW, I did what you said - what your instructions ACTUALLY said to do 🤦‍♂️🤦‍♂️🤦‍♂️ - and it WORKED and I'm so happy RN. Tried "forgot password" button and no response. Here is my log:

```
Attaching to mydomainname_lemmy_1
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:juHZIEzJPCcwuYIqnSSG@postgres:5432/lemmy: could not connect to server: Connection refused
lemmy_1     |   Is the server running on host "postgres" (172.18.0.2) and accepting
lemmy_1     |   TCP/IP connections on port 5432?
lemmy_1     | ', crates/db_schema/src/utils.rs:217:56
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:juHZIEzJPCcwuYIqnSSG@postgres:5432/lemmy: could not connect to server: Connection refused
lemmy_1     |   Is the server running on host "postgres" (172.18.0.2) and accepting
lemmy_1     |   TCP/IP connections on port 5432?
lemmy_1     | ', crates/db_schema/src/utils.rs:217:56
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:juHZIEzJPCcwuYIqnSSG@postgres:5432/lemmy: could not connect to server: Connection refused
lemmy_1     |   Is the server running on host "postgres" (172.18.0.2) and accepting
lemmy_1     |   TCP/IP connections on port 5432?
lemmy_1     | ', crates/db_schema/src/utils.rs:217:56
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | thread 'main' panicked at 'Error connecting to postgres://lemmy:juHZIEzJPCcwuYIqnSSG@postgres:5432/lemmy: could not connect to server: Connection refused
lemmy_1     |   Is the server running on host "postgres" (172.18.0.2) and accepting
lemmy_1     |   TCP/IP connections on port 5432?
lemmy_1     | ', crates/db_schema/src/utils.rs:217:56
lemmy_1     | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy_1     | federation enabled, host is my.domain
lemmy_1     | Starting http server at 0.0.0.0:8536
lemmy_1     | 2023-08-04T02:56:09.122307Z  WARN lemmy_server::root_span_builder: Webfinger regex failed to match
lemmy_1     |    0: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=GET http.scheme="http" http.host=lemmy http.target=/.well-known/webfinger otel.kind="server" request_id=fd4a491d-9374-4e22-a613-3262dd430f91
lemmy_1     |              at src/root_span_builder.rs:16
lemmy_1     | LemmyError { message: None, inner: Webfinger regex failed to match, context: SpanTrace [{ target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=GET http.scheme=\"http\" http.host=lemmy http.target=/.well-known/webfinger otel.kind=\"server\" request_id=fd4a491d-9374-4e22-a613-3262dd430f91", file: "src/root_span_builder.rs", line: 16 }] }
lemmy_1     | 2023-08-04T02:56:09.145596Z  WARN lemmy_server::root_span_builder: Webfinger regex failed to match
lemmy_1     |    0: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=GET http.scheme="http" http.host=lemmy http.target=/.well-known/webfinger otel.kind="server" request_id=c309c94d-cf84-49f4-90af-b06baf402116
lemmy_1     |              at src/root_span_builder.rs:16
lemmy_1     | LemmyError { message: None, inner: Webfinger regex failed to match, context: SpanTrace [{ target: "lemmy_server::root_span_builder", name: "HTTP request", fields: "http.method=GET http.scheme=\"http\" http.host=lemmy http.target=/.well-known/webfinger otel.kind=\"server\" request_id=c309c94d-cf84-49f4-90af-b06baf402116", file: "src/root_span_builder.rs", line: 16 }] }
```

**Comment by dessalines** [comment]
Those errors are old ones from when before you got the DB connected.

No response, does it mean it sent the email, but you didn't receive it? Check your spam folder. 

Could you please ask this in one of the support channels, I don't have time to debug your setup.

**Comment by ticoombs** [comment]
The ansible code has been tested by at least over 200 people and successfully works out-of-the-box. 

If you have more information @anonymoushand for us to investigate a reason why your instance is failing, please provide the docker logs for postfix & lemmy

Otherwise I think we could safely #close it. (as it has already been 4 months)
